<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $student->name }} - Finance Report</title>
    <style>
        body {
            font-family: "DejaVu Sans", sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header img {
            width: 80px;
            height: 80px;
        }
        .header h1 {
            margin: 5px 0 0;
            font-size: 24px;
        }
        .header p {
            margin: 0;
            font-size: 14px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th, td {
            border: 1px solid #aaa;
            padding: 8px;
            text-align: left;
            font-size: 13px;
        }
        th {
            background-color: #f2f2f2;
        }
        .summary {
            margin-top: 30px;
            width: 50%;
            float: right;
        }
        .summary td {
            font-weight: bold;
        }
        .footer {
            position: fixed;
            bottom: 20px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 12px;
        }
        .signature {
            margin-top: 80px;
            text-align: right;
        }
    </style>
</head>
<body>

    <div class="header">
        <img src="{{ public_path('images/logo.png') }}" alt="School Logo">
        <h1>Saint Paul’s Academy</h1>
        <p>Finance Department Report</p>
        <p><strong>Date:</strong> {{ now()->format('d M, Y') }}</p>
    </div>

    <h3>Student Information</h3>
    <table>
        <tr><td><strong>Name:</strong></td><td>{{ $student->name }}</td></tr>
        <tr><td><strong>Admission No:</strong></td><td>{{ $student->admission_no ?? 'N/A' }}</td></tr>
        <tr><td><strong>Class:</strong></td><td>{{ $student->class ?? 'N/A' }}</td></tr>
    </table>

    <h3 style="margin-top:25px;">Fee Breakdown</h3>
    <table>
        <thead>
            <tr>
                <th>Term</th>
                <th>Item</th>
                <th>Amount Due (KSh)</th>
                <th>Amount Paid (KSh)</th>
                <th>Balance (KSh)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($fees as $fee)
                @foreach($fee->breakdowns as $b)
                    <tr>
                        <td>{{ $fee->term }}</td>
                        <td>{{ $b->item_name }}</td>
                        <td>{{ number_format($b->amount_due, 2) }}</td>
                        <td>{{ number_format($b->amount_paid, 2) }}</td>
                        <td>{{ number_format($b->amount_due - $b->amount_paid, 2) }}</td>
                    </tr>
                @endforeach
            @endforeach
        </tbody>
    </table>

    <table class="summary">
        <tr><td>Total Fee:</td><td>KSh {{ number_format($totalDue, 2) }}</td></tr>
        <tr><td>Total Paid:</td><td>KSh {{ number_format($totalPaid, 2) }}</td></tr>
        <tr><td>Balance:</td><td>KSh {{ number_format($balance, 2) }}</td></tr>
    </table>

    <div style="clear:both;"></div>

    <div class="signature">
        <p>_________________________</p>
        <p><strong>Director Signature</strong></p>
    </div>

    <div class="footer">
        Generated by Saint Paul’s Academy | {{ now()->format('d M Y, H:i A') }}
    </div>

</body>
</html>
